# Generated by Django 5.2.1 on 2025-05-27 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_add_revenue_type_to_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost_type', models.CharField(choices=[('contractor', 'Contractor'), ('payroll', 'Payroll'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('software', 'Software/Technology'), ('office', 'Office Supplies'), ('marketing', 'Marketing'), ('travel', 'Travel'), ('professional', 'Professional Services'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly Recurring'), ('one_time', 'One Time'), ('project_duration', 'Spread Over Project Duration')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_contractor', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('is_billable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='monthlycost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlycost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='monthlycost',
            name='project',
        ),
        migrations.RemoveField(
            model_name='recurringcost',
            name='company',
        ),
        migrations.RemoveIndex(
            model_name='contractorexpense',
            name='agency_cont_company_dfe127_idx',
        ),
        migrations.AddField(
            model_name='cost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='agency.company'),
        ),
        migrations.AddField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='agency.project'),
        ),
        migrations.DeleteModel(
            name='MonthlyCost',
        ),
        migrations.DeleteModel(
            name='RecurringCost',
        ),
        migrations.AddIndex(
            model_name='cost',
            index=models.Index(fields=['company', 'start_date'], name='agency_cost_company_d15a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='cost',
            index=models.Index(fields=['cost_type', 'is_contractor'], name='agency_cost_cost_ty_ef4917_idx'),
        ),
    ]
